// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: delivery.proto

package delivery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Combos     []*Combo     `protobuf:"bytes,1,rep,name=Combos,proto3" json:"Combos,omitempty"`
	Hamburgers []*Hamburger `protobuf:"bytes,2,rep,name=Hamburgers,proto3" json:"Hamburgers,omitempty"`
	SideMenus  []*SideMenu  `protobuf:"bytes,3,rep,name=SideMenus,proto3" json:"SideMenus,omitempty"`
	Drinks     []*Drink     `protobuf:"bytes,4,rep,name=Drinks,proto3" json:"Drinks,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetCombos() []*Combo {
	if x != nil {
		return x.Combos
	}
	return nil
}

func (x *Order) GetHamburgers() []*Hamburger {
	if x != nil {
		return x.Hamburgers
	}
	return nil
}

func (x *Order) GetSideMenus() []*SideMenu {
	if x != nil {
		return x.SideMenus
	}
	return nil
}

func (x *Order) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

type Combo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hamburger *Hamburger `protobuf:"bytes,1,opt,name=Hamburger,proto3" json:"Hamburger,omitempty"`
	SideMenu  *SideMenu  `protobuf:"bytes,2,opt,name=SideMenu,proto3" json:"SideMenu,omitempty"`
	Drink     *Drink     `protobuf:"bytes,3,opt,name=Drink,proto3" json:"Drink,omitempty"`
}

func (x *Combo) Reset() {
	*x = Combo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Combo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Combo) ProtoMessage() {}

func (x *Combo) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Combo.ProtoReflect.Descriptor instead.
func (*Combo) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *Combo) GetHamburger() *Hamburger {
	if x != nil {
		return x.Hamburger
	}
	return nil
}

func (x *Combo) GetSideMenu() *SideMenu {
	if x != nil {
		return x.SideMenu
	}
	return nil
}

func (x *Combo) GetDrink() *Drink {
	if x != nil {
		return x.Drink
	}
	return nil
}

type Hamburger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// bans
	Top    int32 `protobuf:"varint,1,opt,name=Top,proto3" json:"Top,omitempty"`
	Middle int32 `protobuf:"varint,2,opt,name=Middle,proto3" json:"Middle,omitempty"`
	Bottom int32 `protobuf:"varint,3,opt,name=Bottom,proto3" json:"Bottom,omitempty"`
	// patty
	Beef    int32 `protobuf:"varint,4,opt,name=Beef,proto3" json:"Beef,omitempty"`
	Chicken int32 `protobuf:"varint,5,opt,name=Chicken,proto3" json:"Chicken,omitempty"`
	Fish    int32 `protobuf:"varint,6,opt,name=Fish,proto3" json:"Fish,omitempty"`
	//vegetable
	Lettuce int32 `protobuf:"varint,7,opt,name=Lettuce,proto3" json:"Lettuce,omitempty"`
	Tomato  int32 `protobuf:"varint,8,opt,name=Tomato,proto3" json:"Tomato,omitempty"`
	Onion   int32 `protobuf:"varint,9,opt,name=Onion,proto3" json:"Onion,omitempty"`
	//ingredient
	Cheese  int32 `protobuf:"varint,10,opt,name=Cheese,proto3" json:"Cheese,omitempty"`
	Pickles int32 `protobuf:"varint,11,opt,name=Pickles,proto3" json:"Pickles,omitempty"`
}

func (x *Hamburger) Reset() {
	*x = Hamburger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hamburger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hamburger) ProtoMessage() {}

func (x *Hamburger) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hamburger.ProtoReflect.Descriptor instead.
func (*Hamburger) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *Hamburger) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *Hamburger) GetMiddle() int32 {
	if x != nil {
		return x.Middle
	}
	return 0
}

func (x *Hamburger) GetBottom() int32 {
	if x != nil {
		return x.Bottom
	}
	return 0
}

func (x *Hamburger) GetBeef() int32 {
	if x != nil {
		return x.Beef
	}
	return 0
}

func (x *Hamburger) GetChicken() int32 {
	if x != nil {
		return x.Chicken
	}
	return 0
}

func (x *Hamburger) GetFish() int32 {
	if x != nil {
		return x.Fish
	}
	return 0
}

func (x *Hamburger) GetLettuce() int32 {
	if x != nil {
		return x.Lettuce
	}
	return 0
}

func (x *Hamburger) GetTomato() int32 {
	if x != nil {
		return x.Tomato
	}
	return 0
}

func (x *Hamburger) GetOnion() int32 {
	if x != nil {
		return x.Onion
	}
	return 0
}

func (x *Hamburger) GetCheese() int32 {
	if x != nil {
		return x.Cheese
	}
	return 0
}

func (x *Hamburger) GetPickles() int32 {
	if x != nil {
		return x.Pickles
	}
	return 0
}

type SideMenu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name int32 `protobuf:"varint,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *SideMenu) Reset() {
	*x = SideMenu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SideMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SideMenu) ProtoMessage() {}

func (x *SideMenu) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SideMenu.ProtoReflect.Descriptor instead.
func (*SideMenu) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *SideMenu) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type Drink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name int32 `protobuf:"varint,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Drink) Reset() {
	*x = Drink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *Drink) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type DeliveryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
}

func (x *DeliveryRequest) Reset() {
	*x = DeliveryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRequest) ProtoMessage() {}

func (x *DeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRequest.ProtoReflect.Descriptor instead.
func (*DeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type DeliveryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNumber string `protobuf:"bytes,1,opt,name=OrderNumber,proto3" json:"OrderNumber,omitempty"`
}

func (x *DeliveryResponse) Reset() {
	*x = DeliveryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResponse) ProtoMessage() {}

func (x *DeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResponse.ProtoReflect.Descriptor instead.
func (*DeliveryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryResponse) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

var File_delivery_proto protoreflect.FileDescriptor

var file_delivery_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x22, 0xc0, 0x01, 0x0a, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x62, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e,
	0x43, 0x6f, 0x6d, 0x62, 0x6f, 0x52, 0x06, 0x43, 0x6f, 0x6d, 0x62, 0x6f, 0x73, 0x12, 0x33, 0x0a,
	0x0a, 0x48, 0x61, 0x6d, 0x62, 0x75, 0x72, 0x67, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x48, 0x61, 0x6d,
	0x62, 0x75, 0x72, 0x67, 0x65, 0x72, 0x52, 0x0a, 0x48, 0x61, 0x6d, 0x62, 0x75, 0x72, 0x67, 0x65,
	0x72, 0x73, 0x12, 0x30, 0x0a, 0x09, 0x53, 0x69, 0x64, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x2e, 0x53, 0x69, 0x64, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x09, 0x53, 0x69, 0x64, 0x65, 0x4d,
	0x65, 0x6e, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e,
	0x44, 0x72, 0x69, 0x6e, 0x6b, 0x52, 0x06, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x91, 0x01,
	0x0a, 0x05, 0x43, 0x6f, 0x6d, 0x62, 0x6f, 0x12, 0x31, 0x0a, 0x09, 0x48, 0x61, 0x6d, 0x62, 0x75,
	0x72, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x48, 0x61, 0x6d, 0x62, 0x75, 0x72, 0x67, 0x65, 0x72, 0x52,
	0x09, 0x48, 0x61, 0x6d, 0x62, 0x75, 0x72, 0x67, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x08, 0x53, 0x69,
	0x64, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x08, 0x53, 0x69, 0x64, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x25, 0x0a, 0x05, 0x44, 0x72,
	0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x2e, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x52, 0x05, 0x44, 0x72, 0x69, 0x6e,
	0x6b, 0x22, 0x89, 0x02, 0x0a, 0x09, 0x48, 0x61, 0x6d, 0x62, 0x75, 0x72, 0x67, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x54, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x54, 0x6f,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x6f, 0x74,
	0x74, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x42, 0x6f, 0x74, 0x74, 0x6f,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x65, 0x65, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x42, 0x65, 0x65, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x46, 0x69, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x46,
	0x69, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x65, 0x74, 0x74, 0x75, 0x63, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4c, 0x65, 0x74, 0x74, 0x75, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x54, 0x6f, 0x6d, 0x61, 0x74, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x54,
	0x6f, 0x6d, 0x61, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x43,
	0x68, 0x65, 0x65, 0x73, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x68, 0x65,
	0x65, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x6b, 0x6c, 0x65, 0x73, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x69, 0x63, 0x6b, 0x6c, 0x65, 0x73, 0x22, 0x1e, 0x0a,
	0x08, 0x53, 0x69, 0x64, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a,
	0x05, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x59, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x50, 0x43, 0x12, 0x19, 0x2e, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x59, 0x75, 0x6a, 0x69, 0x59, 0x61, 0x62, 0x65, 0x2f, 0x67, 0x6f, 0x2d,
	0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x31, 0x5f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x2f, 0x69, 0x6e, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_proto_rawDescOnce sync.Once
	file_delivery_proto_rawDescData = file_delivery_proto_rawDesc
)

func file_delivery_proto_rawDescGZIP() []byte {
	file_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_proto_rawDescData)
	})
	return file_delivery_proto_rawDescData
}

var file_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_delivery_proto_goTypes = []interface{}{
	(*Order)(nil),            // 0: delivery.Order
	(*Combo)(nil),            // 1: delivery.Combo
	(*Hamburger)(nil),        // 2: delivery.Hamburger
	(*SideMenu)(nil),         // 3: delivery.SideMenu
	(*Drink)(nil),            // 4: delivery.Drink
	(*DeliveryRequest)(nil),  // 5: delivery.DeliveryRequest
	(*DeliveryResponse)(nil), // 6: delivery.DeliveryResponse
}
var file_delivery_proto_depIdxs = []int32{
	1, // 0: delivery.Order.Combos:type_name -> delivery.Combo
	2, // 1: delivery.Order.Hamburgers:type_name -> delivery.Hamburger
	3, // 2: delivery.Order.SideMenus:type_name -> delivery.SideMenu
	4, // 3: delivery.Order.Drinks:type_name -> delivery.Drink
	2, // 4: delivery.Combo.Hamburger:type_name -> delivery.Hamburger
	3, // 5: delivery.Combo.SideMenu:type_name -> delivery.SideMenu
	4, // 6: delivery.Combo.Drink:type_name -> delivery.Drink
	0, // 7: delivery.DeliveryRequest.Order:type_name -> delivery.Order
	5, // 8: delivery.DeliveryService.DeliveryRPC:input_type -> delivery.DeliveryRequest
	6, // 9: delivery.DeliveryService.DeliveryRPC:output_type -> delivery.DeliveryResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_delivery_proto_init() }
func file_delivery_proto_init() {
	if File_delivery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delivery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Combo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hamburger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SideMenu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Drink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_proto_depIdxs,
		MessageInfos:      file_delivery_proto_msgTypes,
	}.Build()
	File_delivery_proto = out.File
	file_delivery_proto_rawDesc = nil
	file_delivery_proto_goTypes = nil
	file_delivery_proto_depIdxs = nil
}
