# this .rest file for only apply extesion of vs code.
@hostname=localhost
@port=1234


### 1xハンバーガー ==============================
POST http://{{hostname}}:{{port}}/ HTTP/1.1
Content-Type: application/json

{
    "hamburgers":[
        {
            "top": 1,
            "middle": 0,
            "bottom": 1,
            "beef": 1,
            "chicken": 0,
            "fish": 0,
            "lettuce": 1,
            "tomato": 1,
            "onion": 0,
            "cheese": 1,
            "pickles": 1
        }
    ]
}

### 2xダブルバーガー ==============================
POST http://{{hostname}}:{{port}}/ HTTP/1.1
Content-Type: application/json

{
    "hamburgers":[
        {
            "top": 1,
            "middle": 1,
            "bottom": 1,
            "beef": 2 ,
            "chicken": 0,
            "fish": 0,
            "lettuce": 1,
            "tomato": 1,
            "onion": 0,
            "cheese": 1,
            "pickles": 1
        },
        {
            "top": 1,
            "middle": 1,
            "bottom": 1,
            "beef": 2 ,
            "chicken": 0,
            "fish": 0,
            "lettuce": 1,
            "tomato": 1,
            "onion": 0,
            "cheese": 1,
            "pickles": 1
        }
    ]
}

### 1xダブルバーガー & 1xフィッシュバーガー ==============================
POST http://{{hostname}}:{{port}}/ HTTP/1.1
Content-Type: application/json

{
    "hamburgers":[
        {
            "top": 1,
            "middle": 1,
            "bottom": 1,
            "beef": 2 ,
            "chicken": 0,
            "fish": 0,
            "lettuce": 1,
            "tomato": 1,
            "onion": 0,
            "cheese": 2,
            "pickles": 2
        },
        {
            "top": 1,
            "middle": 1,
            "bottom": 1,
            "beef": 0 ,
            "chicken": 0,
            "fish": 1,
            "lettuce": 1,
            "tomato": 0,
            "onion": 1,
            "cheese": 0,
            "pickles": 1
        }
    ]
}
